server:
  port: 9999

# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: panda
    password: e10adc3949ba59abbe56e057f20f883e
    url: jdbc:mysql://49.235.91.219:3306/getoffer?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  application:
    name: belong-service-gen
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.belong.service.gen.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    capital-mode: false
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: false
    cache-enabled: false
debug: false

sys:
  generator:
    #下方为注解配置
    author: BelongFeng
    email: belongfeng@Gmail.com
    package: com.belong.service
    autoRemovePre: false
    tablePrefix: #去掉的表前缀
    #下方为转换类型 数据库类型: 实体类类型
    datetime: Date
    timestamp: Date
    tinyint: Integer
    smallint: Integer
    mediumint: Integer
    int: Integer
    integer: Integer
    bigint: Long
    float: BigDecimal
    double: BigDecimal
    decimal: BigDecimal
    bit: Boolean
    char: Boolean
    varchar: String
    tinytext: String
    text: String
    mediumtext: String
    longtext: String
    date: Date