# 项目相关配置
project:
  # 名称
  name: getoffer
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2019
  #站点配置
  site:
    host: https://getoffer.xiliangmen.com
    staticHost: https://getoffer.xiliangmen.com
    whiteDomainList: localhost,xiliangmen.com
    siteDirPath: /
  #swagger 文档配置
  swagger:
    title: getoffer微信小程序个人中心服务接口
    description: 开发人员太懒，没有写描述
    contactName: Fengyu
    contactEmail: belongfeng@Gmail.com
    contactUrl: https://getoffer.xiliangmen.com/doc.html
    version: 1.0



mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.belong
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false