server:
  port: 520

spring:
  application:
    name: belong-config
  profiles:
    active: native
  # 配置中心
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

# 注册中心配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://fy:123456@belongEureka13141.com:13141/eureka
  #       defaultZone: http://fy:123456@belongEureka13141.com:7001/eureka/,http://fy:123456@eureka7002.com:7002/eureka/,http://fy:123456@eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'