spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: belong-gateway
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #wxapplet 模块
        - id: belong-wxapplet-websocket
          uri: lb://belong-wxapplet-websocket
          predicates:
            - Path=/wxapplet/websocket/**
          filters:
            # 限流配置
            - StripPrefix=2
            - CacheRequest
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://fy:123456@belongEureka13141.com:13141/eureka
      #defaultZone: http://belongEureka13141.com:13141/eureka/,http://belongEureka13142.com:13142/eureka/,http://belongEureka13143.com:13143/eureka/
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址      

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2500 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #断路器超时时间，默认1000ms

